name: Draft

on:
  workflow_dispatch:
  push:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "kilroy_face_debug/src/**"
      - "kilroy_face_debug/LICENSE"
      - "kilroy_face_debug/README.md"
      - "kilroy_face_debug/poetry.lock"
      - "kilroy_face_debug/pyproject.toml"
      - ".github/workflows/draft.yaml"
      - ".github/release-drafter.yaml"

jobs:
  draft:
    name: Update draft release
    # better to use pinned version here
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
